import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { client } from '../lib/client';
import { Product } from '../types/datasheet';

const Home = (data: Props) => {

  console.log(data.products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world!</h1>
    </div>
  )
}

type Props = {
  products: Product[],
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);
  console.log('product', products)
  
  // const bannerQuery = '*[_type == "banner"]';
  // const bannerData = await client.fetch(bannerQuery);

  return {
    props: {
      products,
    }
  }


}

export default Home;
