import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { client } from '../lib/client';
import { Product } from '../types/datasheet';
import Header from '../components/Header/Index';
import Banner from '../components/Banner/Index';
import { Formatter } from '../lib/useFormatter';

const Home = (data: Props) => {

  const formatter = Formatter();

  return (
    <div className={styles.container}>
      <Head>
        <title>EToolShop - Página inicial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Banner />
    </div>
  )
}

type Props = {
  products: Product[],
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);
  
  

  return {
    props: {
      products,
    }
  }
}

export default Home;
